- name: playbook for localhost
  hosts: localhost
  roles:
    - multipass
  tags: createVms

- name: playbook for azure
  hosts: microanpr
  become: True
  roles:
    - common
    - users
    - docker
  tags: setupWeb

