- name: playbook for localhost
  hosts: localhost
  roles:
    - multipass
  tags: createVms

- name: playbook for vms
  hosts: microanpr
  become: True
  roles:
    - common
    - users
    - docker
    - nodejs
  tags: setupVms

