- hosts: localhost
  connection: local
  tasks:
    - name: Log the event
      debug:
        msg: "Thank you, my friend!"
    - name: Run openalpr1 Installer
      ansible.builtin.shell:
        cmd: ls -la
    
    - name: Create a Multipass VM
      theko2fi.multipass.multipass_vm:
        name: foo
        cpus: 2
        memory: 2G
        disk: 8G
        state: started